                            
#                             
# ▄████▄ ███  ██ ██████ ██    
# ██▄▄██ ██ ▀▄██   ██   ██    
# ██  ██ ██   ██   ██   ██            
#                             
# ▄█████ ▄████▄ █████▄ ▄█████ 
# ██     ██▄▄██ ██▄▄█▀ ▀▀▀▄▄▄ 
# ▀█████ ██  ██ ██     █████▀ 
#                
#        - TeamMT & Kre0lidge              

# This is to allow for short messages like "WOW" or "GG"
# Ex: 4 = Message containing less than 4 characters will be ignored
allow-messages-under: 4 

# Any message containing more than x% uppercase letters will be modified
# Ex: 10 = 10% uppercase is the threshold
ratio: 10

# If true, the plugin will not notify the player when their message is modified
silent: false

# Enables console logging for captured chat messages and filtering actions
debug: false